Repository jjsOrganization/server, pull requests merged in 2024-04, with the labels that each got.

#3 ✨ Feat: 채팅방 리스트 반환형 교체
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/kafka/ConsumerService.java
Labels: :sparkles: feature

#5 🐛 채팅방 리스트 반환형 에러 수정
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/WebMvcConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/ChatRoomDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/chat/ChatRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
  src/main/resources/application.yml
Labels: :bug: bug, :recycle: refactor

#6 🐛 fix: branch reopen 이후 close
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
Labels: :bug: bug

#10 🚀[feature] 디자이너와 구매자 이메일 조회 api 추가
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/chat/ChatRoomController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Completelist.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Progressmanagement.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Purchaselist.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Question.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Revenuetally.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Review.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Watersaved.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/Watersavedtally.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/response/ChatEmailDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/reformrequest/ReformRequestRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#13 Feature/11
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/estimate/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/estimate/Estimate.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/estimate/EstimateImage.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/estimate/EstimateStatus.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/portfolio/Portfolio.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/product/Product.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reformrequest/ReformRequest.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/estimate/request/EstimateRequestDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/estimate/response/EstimateResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/estimate/EstimateImgRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/estimate/EstimateRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/estimate/EstimateService.java
Labels: :sparkles: feature, :recycle: refactor

#15 :rocket: Feature: 구매자의 견적서 수락 및 거절 API
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/estimate/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/estimate/EstimateService.java
Labels: :sparkles: feature

#17 :hammer: 파일 구조 변경
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/chat/ChatRoomController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/estimate/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/estimate/Estimate.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/estimate/EstimateImage.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/estimate/EstimateStatus.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/reformrequest/ReformRequest.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/reformrequest/ReformRequestImage.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/reformrequest/ReformRequestStatus.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/estimate/response/EstimateResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestCheckPurchaserDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestImgDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/estimate/EstimateImgRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/estimate/EstimateRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/reformrequest/ReformRequestImgRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/reformrequest/ReformRequestRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/estimate/EstimateService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/reformrequest/ReformRequestService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/s3/S3Service.java
Labels: :recycle: refactor

#20 :recycle: Refactor: 리폼 요청 내역 조회시 반환 값 수정
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/estimate/Estimate.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/reformrequest/ReformRequest.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/reformrequest/ReformRequestRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/estimate/EstimateService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/reformrequest/ReformRequestService.java
Labels: :recycle: refactor

#21 :hammer: Refactor: 리폼 요청 내역 조회시 반환 값 수정(상품 id 추가)
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reformrequest/ReformRequestResponseDTO.java
Labels: :hammer: refactor

#23 [Feature/18] 리폼 형상관리 API 작성
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/ProgressManagementController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/estimate/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/ProgressStatus.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/Progressmanagement.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reform/request/ProgressImgRequestDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/ProgressRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/ProgressManagementService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/estimate/EstimateService.java
Labels: :sparkles: feature, :hammer: refactor

#26 🔨 Refactor: gradle.yml 파일 수정
  .github/workflows/gradle.yml
Labels: :hammer: refactor

#28 🔨 Refactor: 채팅방 생성시 필요한 파라미터 '상품ID' 추가
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/chat/ChatRoomController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/chat/Chat.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/ChatRoomDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
Labels: :hammer: refactor

#29 :hammer: Refactor: gradle.yml 파일 수정
  .github/workflows/gradle.yml
Labels: :hammer: refactor

#32 🔨 Refactor: 참여중인 채팅방 리스트 조회 API 수정(디자이너 추가)
  .github/workflows/gradle.yml
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/product/AuthenticationFacade.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/product/AuthenticationFacadeImpl.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/chat/ChatRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
Labels: :hammer: refactor

#36 💻 CI/CD: gradle.yml수정
  .github/workflows/gradle.yml
Labels: :computer: ci

#37 💻 CI/CD: gradle.yml수정
  .github/workflows/gradle.yml
Labels: :computer: ci

#34 🔨 Refactor: 채팅방 생성에 필요한 정보 수정( 의뢰 번호 추가 )
  .github/workflows/gradle.yml
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/chat/Chat.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/ChatRoomDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/chat/ChatService.java
Labels: :hammer: refactor

#38 :computer: CI/CD: gradle.yml 파일 수정 및 Dockerfile 위치 변경
  .dockerignore
  .github/workflows/gradle.yml
  Dockerfile
Labels: :computer: ci

#39 💻 CI/CD: gradle.yml 수정
  .github/workflows/gradle.yml
Labels: :computer: ci

#40 💻 CI/CD: gradle.yml 수정
  .github/workflows/gradle.yml
Labels: :computer: ci

#41 💻 CI/CD: gradle.yml 수정
  .github/workflows/gradle.yml
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/ChatRoomDTO.java
Labels: :computer: ci

#42 🚀 feature 구매자가 리폼 수락 시 진행되는 주문 관련 API
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/reform/estimate/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/estimate/Estimate.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/order/ReformOrder.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/order/ReformOrderStatus.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reform/estimate/request/EstimateRequestDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reform/estimate/request/ReformOrderRequestDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reform/estimate/response/EstimateResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/reform/estimate/response/ReformOrderResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/repository/reform/order/ReformOrderRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/reform/estimate/EstimateService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/service/reform/progressmanagement/ProgressManagementService.java
Labels: :sparkles: feature

#44 :bug: Bug: chatRoomDTO set값 수정 #43
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/dto/chat/ChatRoomDTO.java
Labels: :bug: bug

#48 🔨 Refactor: /chatroom GET요청 구매자 권한 추가
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
Labels: :hammer: refactor

#50 🐛 Bug: 디자이너 채팅방 리스트 조회 오류 권한 수정
  .github/workflows/gradle.yml
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/SecurityConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/controller/chat/ChatRoomController.java
Labels: :bug: bug

#53 🔨 Refactor: ACCESS_TOKEN_EXPIRE_TIME 2분으로 임시 수정 #52
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/jwt/provider/JwtTokenProvider.java
Labels: :hammer: refactor

#55 🔨 Refactor: webConfig 변경
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/WebConfig.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/WebMvcConfig.java
Labels: :hammer: refactor

#57 💻 CI/CD: gradle.yml 수정
  .github/workflows/gradle.yml
Labels: :computer: ci

#59 🐛 Bug: CORS 에러 수정
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: :bug: bug

#60 🐛 Bug: cors 에러 수정
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: :bug: bug

#63 🐛 Bug:프로젝트 구조 변경 후 발생한 경로 오류 수정
  .github/workflows/gradle.yml
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/order/repository/CustomOrderRepositoryImpl.java
Labels: :bug: bug

#64 🐛 Bug:프로젝트 구조 변경 후 경로 오류 수정
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/order/repository/CustomOrderRepositoryImpl.java
Labels: :bug: bug

#66 :hammer: Refactor: ACCESS_TOKEN_EXPIRE_TIME 2시간으로 복구 #65
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/global/jwt/provider/JwtTokenProvider.java
Labels: :hammer: refactor

#70 :bug: Bug: 견적서 조회 api requestNumber로 조회하는 로직으로 변경
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/controller/EstimateController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/dto/response/EstimateResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/repository/EstimateRepository.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/service/EstimateService.java
Labels: :bug: bug

#72 :rocket: Feature: 요청서id로 견적서id 조회 API #71
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/controller/ReformRequestController.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/dto/response/GetEstimateNumberResponseDTO.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/domain/reform/service/ReformRequestService.java
  src/main/java/com/jjs/ClothingInventorySaleReformPlatform/global/config/SecurityConfig.java
Labels: :sparkles: feature
